name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  flare_flutter:
  gradient_text: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight : 700
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
  assets:
    - dottedsecond.flr
    - wallpaper.jpeg
    - sunset.jpeg
    - sunrise.jpeg
    - cloudy.jpeg
    - foggy.jpeg
    - rainy.jpeg
    - snowy.jpeg
    - thunderstorm.jpeg
    - sunny.jpeg
